// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqeWvLQHwrjJrl0pZDV5h8F_I26kjHel0',
    appId: '1:361327892806:web:da9e10ad92fd84d7f0ad47',
    messagingSenderId: '361327892806',
    projectId: 'ecommerce-store-5e89a',
    authDomain: 'ecommerce-store-5e89a.firebaseapp.com',
    storageBucket: 'ecommerce-store-5e89a.appspot.com',
    measurementId: 'G-S08PYBNK5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARntpnUJRLVMAvi2fH7uyX1KyvH3RyTP4',
    appId: '1:361327892806:android:ad6e18ac85cedac9f0ad47',
    messagingSenderId: '361327892806',
    projectId: 'ecommerce-store-5e89a',
    storageBucket: 'ecommerce-store-5e89a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGatRH0BkyKqvMoqDtppKWaZEozvs-OUo',
    appId: '1:361327892806:ios:e7f34dac6e92f001f0ad47',
    messagingSenderId: '361327892806',
    projectId: 'ecommerce-store-5e89a',
    storageBucket: 'ecommerce-store-5e89a.appspot.com',
    iosBundleId: 'com.example.ecommerceStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGatRH0BkyKqvMoqDtppKWaZEozvs-OUo',
    appId: '1:361327892806:ios:e7f34dac6e92f001f0ad47',
    messagingSenderId: '361327892806',
    projectId: 'ecommerce-store-5e89a',
    storageBucket: 'ecommerce-store-5e89a.appspot.com',
    iosBundleId: 'com.example.ecommerceStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqeWvLQHwrjJrl0pZDV5h8F_I26kjHel0',
    appId: '1:361327892806:web:335f342c945c4fd5f0ad47',
    messagingSenderId: '361327892806',
    projectId: 'ecommerce-store-5e89a',
    authDomain: 'ecommerce-store-5e89a.firebaseapp.com',
    storageBucket: 'ecommerce-store-5e89a.appspot.com',
    measurementId: 'G-E9PQ0YDEVX',
  );
}
